sudo: required
services:
  - docker

before_install:
  - docker build ugatza/react-test -f ./client/Dockerfile.dev ./client

script:
- docker run -e CI=true ugatza/react-test npm test

after_success:
  - docker build -t ugatza/multi-client ./client
  - docker build -t ugatza/multi-nginx ./nginx
  - docker build -t ugatza/multi-server ./server
  - docker build -t ugatza/multi-worker ./worker